#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:
    
services:
  web_admin:
    container_name: {CONTAINER_NAME}
    image: {CONTAINER_IMAGE}:1.0
    mem_limit: 200m
    networks:
        - basic
    ports:
      - "127.0.0.1:{PORT}:{PORT}"
    #tty: true
    #command: /bin/bash
